// Plan export helpers — plain-text rendering for email / clipboard / share,
// and trigger for browser-native print (which doubles as Save-as-PDF on
// every modern browser).

/**
 * Render a WeeklyPlan as a human-readable plain-text block. Same shape used
 * for clipboard, mailto: bodies, and navigator.share text. Categorized,
 * matches the on-screen Menu tab structure.
 */
export function formatPlanAsText(plan) {
  if (!plan) return ''
  const lines = []
  const start = plan.days?.[0]?.date
  const end = plan.days?.[plan.days.length - 1]?.date
  if (start && end) {
    lines.push(`Ruhi Weekly Plan — ${formatDate(start)} to ${formatDate(end)}`)
  } else {
    lines.push('Ruhi Weekly Plan')
  }
  lines.push('')

  // Phase progression — one line summary
  if (plan.days?.length) {
    const phases = plan.days
      .map((d) => `${d.dayLabel} ${d.phase} d${d.cycleDay}`)
      .join('  ·  ')
    lines.push(`Phases: ${phases}`)
    lines.push('')
  }

  // Phase-transition callouts + seed cycling note
  if (plan.phaseTransitionCallouts?.length || plan.seedCyclingNote) {
    lines.push('NOTES')
    plan.phaseTransitionCallouts?.forEach((c) => lines.push(`- ${c}`))
    if (plan.seedCyclingNote) lines.push(`- ${plan.seedCyclingNote}`)
    lines.push('')
  }

  // Menu sections
  const sections = [
    ['BREAKFASTS', plan.menu?.breakfasts],
    ['LUNCHES', plan.menu?.lunches],
    ['SNACKS', plan.menu?.snacks],
    ['DINNERS', plan.menu?.dinners],
  ]
  for (const [title, items] of sections) {
    if (!items?.length) continue
    lines.push(title)
    for (const item of items) {
      lines.push(`- ${item.title}${item.cookTime ? ` (${item.cookTime})` : ''}`)
      if (item.macros) lines.push(`    ${item.macros}${item.calories ? ` · ${item.calories}` : ''}`)
    }
    lines.push('')
  }

  // Drinks grouped by time of day
  if (plan.menu?.drinks?.length) {
    lines.push('DRINKS')
    const grouped = { morning: [], afternoon: [], evening: [] }
    plan.menu.drinks.forEach((d) => grouped[d.timeOfDay]?.push(d))
    for (const tod of ['morning', 'afternoon', 'evening']) {
      const list = grouped[tod]
      if (!list?.length) continue
      lines.push(`  ${tod}:`)
      for (const d of list) {
        lines.push(`  - ${d.title}${d.reason ? ` — ${d.reason}` : ''}`)
      }
    }
    lines.push('')
  }

  // Shopping list grouped by category
  if (plan.shoppingList?.length) {
    lines.push('SHOPPING LIST')
    const cats = {}
    plan.shoppingList.forEach((it) => {
      const cat = it.category || 'other'
      if (!cats[cat]) cats[cat] = []
      cats[cat].push(it)
    })
    const order = ['produce', 'protein', 'dairy', 'pantry', 'frozen', 'other']
    for (const cat of order) {
      if (!cats[cat]?.length) continue
      lines.push(`  ${cat}:`)
      for (const it of cats[cat]) {
        const tag = it.inPantry ? ' (already in pantry)' : ''
        lines.push(`  - ${it.quantity ? `${it.quantity} ` : ''}${it.name}${tag}`)
      }
    }
    lines.push('')
  }

  lines.push('— Generated by Ruhi · tryruhi.ai')
  return lines.join('\n')
}

// Trigger native browser print. The print stylesheet in globals.css strips
// app chrome (NavMenu, ThemePicker, dev tools) so the printed output is
// just the plan content. Users can pick "Save as PDF" from the print
// dialog — no PDF library required.
export function printPlan() {
  if (typeof window === 'undefined') return
  window.print()
}

// Mail-to launcher — opens user's default mail client with the formatted
// plan as the body. Subject pre-filled with the week range.
export function emailPlan(plan) {
  if (typeof window === 'undefined') return
  const start = plan?.days?.[0]?.date
  const end = plan?.days?.[plan?.days?.length - 1]?.date
  const subjectRange = start && end ? ` ${formatDate(start)}–${formatDate(end)}` : ''
  const subject = encodeURIComponent(`Ruhi weekly plan${subjectRange}`)
  const body = encodeURIComponent(formatPlanAsText(plan))
  window.location.href = `mailto:?subject=${subject}&body=${body}`
}

// Web Share API — native iOS / Android share sheet. Caller should
// feature-detect via `typeof navigator.share === 'function'` before showing
// the option, since desktop browsers rarely support it.
export async function sharePlan(plan) {
  if (typeof navigator === 'undefined' || typeof navigator.share !== 'function') {
    return { ok: false, reason: 'unsupported' }
  }
  try {
    await navigator.share({
      title: 'My Ruhi weekly plan',
      text: formatPlanAsText(plan),
    })
    return { ok: true }
  } catch (err) {
    // User cancelled or share failed — non-fatal
    return { ok: false, reason: err?.name === 'AbortError' ? 'cancelled' : 'failed' }
  }
}

function formatDate(iso) {
  if (!iso) return ''
  const d = new Date(`${iso}T00:00:00`)
  return d.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })
}
