'use client'

import { useEffect, useRef, useState } from 'react'
import {
  GROCERY_SERVICES,
  formatHumanList,
  extractItemName,
} from '@/lib/groceryDeepLinks'

/**
 * Bottom-sheet modal for sending a generated shopping list to the user's
 * grocery service of choice (or to clipboard / email / native share).
 *
 * All grocery handoffs use public search-URL deep links — no APIs, no
 * approval. The destination service opens with the items pre-searched.
 *
 * Props:
 *   open    — boolean
 *   onClose — () => void
 *   items   — array of formatted strings, e.g. ["500g chicken breast", ...]
 */
export default function SendShoppingListSheet({ open, onClose, items }) {
  const sheetRef = useRef(null)
  const [copied, setCopied] = useState(false)
  const [shareSupported, setShareSupported] = useState(false)

  // Feature-detect navigator.share once on mount (client-only).
  useEffect(() => {
    if (typeof navigator !== 'undefined' && typeof navigator.share === 'function') {
      setShareSupported(true)
    }
  }, [])

  // Close on outside click + Escape key.
  useEffect(() => {
    if (!open) return
    function onPointer(e) {
      if (sheetRef.current && !sheetRef.current.contains(e.target)) {
        onClose()
      }
    }
    function onKey(e) {
      if (e.key === 'Escape') onClose()
    }
    document.addEventListener('mousedown', onPointer)
    document.addEventListener('touchstart', onPointer)
    document.addEventListener('keydown', onKey)
    return () => {
      document.removeEventListener('mousedown', onPointer)
      document.removeEventListener('touchstart', onPointer)
      document.removeEventListener('keydown', onKey)
    }
  }, [open, onClose])

  // Reset "Copied!" affordance whenever the sheet reopens.
  useEffect(() => {
    if (open) setCopied(false)
  }, [open])

  if (!open) return null

  // Old behavior joined ALL items into one search-param — Target/Safeway 404'd
  // on the over-long URL, Amazon/Kroger interpreted the whole string as one
  // search and returned the first matching item. There's no public deep link
  // for any of these brands that prefills a multi-item cart (that's what the
  // Instacart Connect API is for, Phase 2). So: open the FIRST item's search
  // and put the full list on the clipboard simultaneously, with a clear nudge.
  const firstItemQuery = extractItemName(items[0] || '')
  const humanList = formatHumanList(items)

  async function openService(service) {
    if (!firstItemQuery) {
      onClose()
      return
    }
    // Best-effort clipboard copy. Some browsers require a user-gesture for
    // clipboard.writeText — clicking a service button qualifies. Failures are
    // non-fatal; the user can still hit "Copy list" below.
    try {
      await navigator.clipboard?.writeText(humanList)
    } catch {
      // ignore — store still opens
    }
    const url = service.buildUrl(firstItemQuery)
    window.open(url, '_blank', 'noopener,noreferrer')
    onClose()
  }

  async function copyList() {
    try {
      await navigator.clipboard.writeText(humanList)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Fallback for browsers without Clipboard API permission
      setCopied(false)
    }
  }

  function emailList() {
    const subject = encodeURIComponent('Shopping list from Ruhi')
    const body = encodeURIComponent(`${humanList}\n\nGenerated by Ruhi`)
    window.location.href = `mailto:?subject=${subject}&body=${body}`
  }

  async function shareList() {
    try {
      await navigator.share({
        title: 'Shopping list from Ruhi',
        text: humanList,
      })
      onClose()
    } catch {
      // User cancelled or share failed — leave sheet open
    }
  }

  return (
    <div
      className="fixed inset-0 z-[60] flex items-end sm:items-center justify-center bg-black/40 backdrop-blur-sm"
      role="dialog"
      aria-modal="true"
      aria-labelledby="send-list-title"
    >
      <div
        ref={sheetRef}
        className="w-full sm:max-w-md sm:rounded-2xl rounded-t-2xl bg-ruhi-cream shadow-2xl
                   border-t sm:border border-white/60 max-h-[88vh] overflow-y-auto screen-enter"
      >
        <div className="px-5 pt-5 pb-3 flex items-center justify-between">
          <div>
            <h2 id="send-list-title" className="text-base text-ruhi-deep font-medium">
              Send shopping list
            </h2>
            <p className="text-xs text-ruhi-earth mt-0.5">
              {items.length} item{items.length === 1 ? '' : 's'} · pick where to shop
            </p>
          </div>
          <button
            onClick={onClose}
            aria-label="Close"
            className="text-ruhi-earth hover:text-ruhi-deep w-8 h-8 rounded-full
                       hover:bg-white/60 flex items-center justify-center transition-colors"
          >
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
              <line x1="18" y1="6" x2="6" y2="18"/>
              <line x1="6" y1="6" x2="18" y2="18"/>
            </svg>
          </button>
        </div>

        {items.length > 1 && firstItemQuery && (
          <div className="mx-5 mb-3 p-3 rounded-xl bg-ruhi-peach/30 border border-ruhi-peach/40 text-xs text-ruhi-deep leading-relaxed">
            Tap a store below — your first item ({firstItemQuery}) opens in
            search and your full list copies to your clipboard. Paste as you
            shop. (Real cart-prefill is on the post-cohort roadmap.)
          </div>
        )}

        <div className="px-5 pb-2">
          <h3 className="text-[10px] uppercase tracking-widest text-ruhi-earth mb-2">
            Shop online
          </h3>
          <div className="grid grid-cols-2 gap-2">
            {GROCERY_SERVICES.map((service) => (
              <button
                key={service.id}
                onClick={() => openService(service)}
                className="text-left p-3 rounded-xl bg-white/70 border border-white/60
                           hover:bg-white hover:shadow-sm transition-all"
              >
                <div className="text-sm text-ruhi-deep font-medium">{service.name}</div>
                <div className="text-[10px] text-ruhi-earth mt-0.5 leading-tight">
                  {service.tagline}
                </div>
              </button>
            ))}
          </div>
        </div>

        <div className="px-5 pt-4 pb-5">
          <h3 className="text-[10px] uppercase tracking-widest text-ruhi-earth mb-2">
            Other ways
          </h3>
          <div className="flex flex-col gap-2">
            <FallbackButton onClick={copyList} label={copied ? 'Copied!' : 'Copy list'} />
            <FallbackButton onClick={emailList} label="Email me the list" />
            {shareSupported && (
              <FallbackButton onClick={shareList} label="Share…" />
            )}
          </div>
        </div>
      </div>
    </div>
  )
}

function FallbackButton({ onClick, label }) {
  return (
    <button
      onClick={onClick}
      className="w-full py-2.5 rounded-xl text-sm text-ruhi-deep bg-white/70
                 border border-white/60 hover:bg-white hover:shadow-sm transition-all"
    >
      {label}
    </button>
  )
}
